REPLACE INTO `role` VALUES (1,'USER');
REPLACE INTO `role` VALUES (2,'ADMIN');
REPLACE INTO `bonus` VALUES (1,'Kein Bonusprogramm');
REPLACE INTO `bonus` VALUES (2,'Heavy User');
REPLACE INTO `bonus` VALUES (3,'10% Rabatt auf nächste Fahrt.');
REPLACE INTO `bonus` VALUES (4,'Nächste Fahrt umsonst.');
REPLACE INTO `repeats` VALUES (1,'Einmalig');
REPLACE INTO `repeats` VALUES (2,'Täglich');
REPLACE INTO `repeats` VALUES (3,'Wöchentlich');
REPLACE INTO `repeats` VALUES (4,'Monatlich');